//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaussDB.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GaussDBStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GaussDBStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.GaussDB.Properties.GaussDBStrings", typeof(GaussDBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be positive. 的本地化字符串。
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read infinity value since GaussDB.DisableDateTimeInfinityConversions is enabled. 的本地化字符串。
        /// </summary>
        internal static string CannotReadInfinityValue {
            get {
                return ResourceManager.GetString("CannotReadInfinityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read interval values with non-zero months as TimeSpan, since that type doesn&apos;t support months. Consider using NodaTime Period which better corresponds to PostgreSQL interval, or read the value as GaussDBInterval, or transform the interval to not contain months or years in PostgreSQL before reading it. 的本地化字符串。
        /// </summary>
        internal static string CannotReadIntervalWithMonthsAsTimeSpan {
            get {
                return ResourceManager.GetString("CannotReadIntervalWithMonthsAsTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When registering a password provider, a password or password file may not be set. 的本地化字符串。
        /// </summary>
        internal static string CannotSetBothPasswordProviderAndPassword {
            get {
                return ResourceManager.GetString("CannotSetBothPasswordProviderAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple kinds of password providers were found, only one kind may be configured per DbDataSource. 的本地化字符串。
        /// </summary>
        internal static string CannotSetMultiplePasswordProviderKinds {
            get {
                return ResourceManager.GetString("CannotSetMultiplePasswordProviderKinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When creating a multi-host data source, TargetSessionAttributes cannot be specified. Create without TargetSessionAttributes, and then obtain DataSource wrappers from it. Consult the docs for more information. 的本地化字符串。
        /// </summary>
        internal static string CannotSpecifyTargetSessionAttributes {
            get {
                return ResourceManager.GetString("CannotSpecifyTargetSessionAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RootCertificate cannot be used in conjunction with UserCertificateValidationCallback; when registering a validation callback, perform whatever validation you require in that callback. 的本地化字符串。
        /// </summary>
        internal static string CannotUseSslRootCertificateWithUserCallback {
            get {
                return ResourceManager.GetString("CannotUseSslRootCertificateWithUserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SslMode.{0} cannot be used in conjunction with UserCertificateValidationCallback; when registering a validation callback, perform whatever validation you require in that callback. 的本地化字符串。
        /// </summary>
        internal static string CannotUseSslVerifyWithUserCallback {
            get {
                return ResourceManager.GetString("CannotUseSslVerifyWithUserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValidationRootCertificateCallback cannot be used in conjunction with UserCertificateValidationCallback; when registering a validation callback, perform whatever validation you require in that callback. 的本地化字符串。
        /// </summary>
        internal static string CannotUseValidationRootCertificateCallbackWithUserCallback {
            get {
                return ResourceManager.GetString("CannotUseValidationRootCertificateCallbackWithUserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; required dynamic JSON serialization, which requires an explicit opt-in; call &apos;{1}&apos; on &apos;{2}&apos; or GaussDBConnection.GlobalTypeMapper (see https://www.GaussDB.org/doc/types/json.html and the 8.0 release notes for more details). Alternatively, if you meant to use Newtonsoft JSON.NET instead of System.Text.Json, call UseJsonNet() instead.
        /// 的本地化字符串。
        /// </summary>
        internal static string DynamicJsonNotEnabled {
            get {
                return ResourceManager.GetString("DynamicJsonNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full-text search isn&apos;t enabled; please call {0} on {1} to enable full-text search. 的本地化字符串。
        /// </summary>
        internal static string FullTextSearchNotEnabled {
            get {
                return ResourceManager.GetString("FullTextSearchNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrated security hasn&apos;t been enabled; please call {0} on GaussDBSlimDataSourceBuilder to enable it. 的本地化字符串。
        /// </summary>
        internal static string IntegratedSecurityDisabled {
            get {
                return ResourceManager.GetString("IntegratedSecurityDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ltree isn&apos;t enabled; please call {0} on {1} to enable LTree. 的本地化字符串。
        /// </summary>
        internal static string LTreeNotEnabled {
            get {
                return ResourceManager.GetString("LTreeNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multirange arrays aren&apos;t enabled; please call {0} on {1} to enable arrays for multiranges. 的本地化字符串。
        /// </summary>
        internal static string MultirangeArraysNotEnabled {
            get {
                return ResourceManager.GetString("MultirangeArraysNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiranges aren&apos;t enabled; please call {0} on {1} to enable multiranges. 的本地化字符串。
        /// </summary>
        internal static string MultirangesNotEnabled {
            get {
                return ResourceManager.GetString("MultirangesNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No multirange type could be found in the database for subtype {0}. 的本地化字符串。
        /// </summary>
        internal static string NoMultirangeTypeFound {
            get {
                return ResourceManager.GetString("NoMultirangeTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection and transaction access is not supported on batches created from DbDataSource. 的本地化字符串。
        /// </summary>
        internal static string NotSupportedOnDataSourceBatch {
            get {
                return ResourceManager.GetString("NotSupportedOnDataSourceBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection and transaction access is not supported on commands created from DbDataSource. 的本地化字符串。
        /// </summary>
        internal static string NotSupportedOnDataSourceCommand {
            get {
                return ResourceManager.GetString("NotSupportedOnDataSourceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The right type of password provider (sync or async) was not found. 的本地化字符串。
        /// </summary>
        internal static string PasswordProviderMissing {
            get {
                return ResourceManager.GetString("PasswordProviderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When using CommandType.StoredProcedure, all positional parameters must come before named parameters. 的本地化字符串。
        /// </summary>
        internal static string PositionalParameterAfterNamed {
            get {
                return ResourceManager.GetString("PositionalParameterAfterNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range arrays aren&apos;t enabled; please call {0} on {1} to enable arrays for ranges. 的本地化字符串。
        /// </summary>
        internal static string RangeArraysNotEnabled {
            get {
                return ResourceManager.GetString("RangeArraysNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranges aren&apos;t enabled; please call {0} on {1} to enable ranges. 的本地化字符串。
        /// </summary>
        internal static string RangesNotEnabled {
            get {
                return ResourceManager.GetString("RangesNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not read a PostgreSQL record. If you&apos;re attempting to read a record as a .NET tuple, call &apos;{0}&apos; on &apos;{1}&apos; or GaussDBConnection.GlobalTypeMapper (see https://www.GaussDB.org/doc/types/basic.html and the 8.0 release notes for more details). If you&apos;re reading a record as a .NET object array using GaussDBSlimDataSourceBuilder, call &apos;{2}&apos;.
        /// 的本地化字符串。
        /// </summary>
        internal static string RecordsNotEnabled {
            get {
                return ResourceManager.GetString("RecordsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both sync and async connection initializers must be provided. 的本地化字符串。
        /// </summary>
        internal static string SyncAndAsyncConnectionInitializersRequired {
            get {
                return ResourceManager.GetString("SyncAndAsyncConnectionInitializersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both sync and async password providers must be provided. 的本地化字符串。
        /// </summary>
        internal static string SyncAndAsyncPasswordProvidersRequired {
            get {
                return ResourceManager.GetString("SyncAndAsyncPasswordProvidersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write DateTime with Kind=UTC to PostgreSQL type &apos;{0}&apos;, consider using &apos;{1}&apos;. Note that it&apos;s not possible to mix DateTimes with different Kinds in an array, range, or multirange. 的本地化字符串。
        /// </summary>
        internal static string TimestampNoDateTimeUtc {
            get {
                return ResourceManager.GetString("TimestampNoDateTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write DateTime with Kind={0} to PostgreSQL type &apos;{1}&apos;, only UTC is supported. Note that it&apos;s not possible to mix DateTimes with different Kinds in an array, range, or multirange. 的本地化字符串。
        /// </summary>
        internal static string TimestampTzNoDateTimeUnspecified {
            get {
                return ResourceManager.GetString("TimestampTzNoDateTimeUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport security hasn&apos;t been enabled; please call {0} on GaussDBSlimDataSourceBuilder to enable it. 的本地化字符串。
        /// </summary>
        internal static string TransportSecurityDisabled {
            get {
                return ResourceManager.GetString("TransportSecurityDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading and writing unmapped enums requires an explicit opt-in; call &apos;{0}&apos; on &apos;{1}&apos; or GaussDBConnection.GlobalTypeMapper (see https://www.GaussDB.org/doc/types/enums_and_composites.html and the 8.0 release notes for more details). 的本地化字符串。
        /// </summary>
        internal static string UnmappedEnumsNotEnabled {
            get {
                return ResourceManager.GetString("UnmappedEnumsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading and writing unmapped ranges and multiranges requires an explicit opt-in; call &apos;{0}&apos; on &apos;{1}&apos; or GaussDBConnection.GlobalTypeMapper (see https://www.GaussDB.org/doc/types/ranges.html and the 8.0 release notes for more details). 的本地化字符串。
        /// </summary>
        internal static string UnmappedRangesNotEnabled {
            get {
                return ResourceManager.GetString("UnmappedRangesNotEnabled", resourceCulture);
            }
        }
    }
}
